### ISSUE TITLE
重启后登录失败

### ISSUE THREAD

**Issue by zhanyeye** [fengberd/SakuraFrpLauncher#6]
您好，SakuraFrpLauncher 真的非常好用。可最近突然发现重启后登录失败。彻底退出后才可以重新登录
异常为 : `System.Net.WebException: The remote name could not be resolved: 'api.natfrp.com'`
运行模式为“系统服务”，请问这是我本地网络的原因嘛
```
Service 2020/10/26 19:37:05 ERROR 用户登录失败: 出现未知错误
System.Net.WebException: The remote name could not be resolved: 'api.natfrp.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SakuraFrpService.Natfrp.<Request>d__4`1.MoveNext()
```

**Comment by fengberd** [comment]
系统 DNS 问题, 请自行检查是否能正常解析 api.natfrp.com

**Comment by zhanyeye** [comment]
非常感谢✨，我去排查一下

**Comment by fengberd** [comment]
可以考虑把服务运行模式改成 `自动 (延迟启动)`, 应该可以缓解问题
但理论上重启后会不断重试登录直到成功或服务器明确返回凭据无效, 你也可以考虑等等看能不能成功登录

**Comment by zhanyeye** [comment]
谢谢呀。应该是我这边的问题，将wifi 换成网线后，问题又消失了。我猜是不是重启后网络还没连上，就发送请求了。（我关闭了win10的快速启动，有可能wifi驱动还没启动）
（发现域名解析失败后，程序直接抛异常了，没有继续发送请求）
谢谢您提供的思路，帮助我解决了问题(≧∇≦)ﾉ
